package com.alct.integration.lbs.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PhoneLbsTraceEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public PhoneLbsTraceEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andLocateTimeIsNull() {
            addCriterion("locate_time is null");
            return (Criteria) this;
        }

        public Criteria andLocateTimeIsNotNull() {
            addCriterion("locate_time is not null");
            return (Criteria) this;
        }

        public Criteria andLocateTimeEqualTo(Date value) {
            addCriterion("locate_time =", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeNotEqualTo(Date value) {
            addCriterion("locate_time <>", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeGreaterThan(Date value) {
            addCriterion("locate_time >", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("locate_time >=", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeLessThan(Date value) {
            addCriterion("locate_time <", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeLessThanOrEqualTo(Date value) {
            addCriterion("locate_time <=", value, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeIn(List<Date> values) {
            addCriterion("locate_time in", values, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeNotIn(List<Date> values) {
            addCriterion("locate_time not in", values, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeBetween(Date value1, Date value2) {
            addCriterion("locate_time between", value1, value2, "locateTime");
            return (Criteria) this;
        }

        public Criteria andLocateTimeNotBetween(Date value1, Date value2) {
            addCriterion("locate_time not between", value1, value2, "locateTime");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeIsNull() {
            addCriterion("origin_latitude is null");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeIsNotNull() {
            addCriterion("origin_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeEqualTo(BigDecimal value) {
            addCriterion("origin_latitude =", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("origin_latitude <>", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeGreaterThan(BigDecimal value) {
            addCriterion("origin_latitude >", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("origin_latitude >=", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeLessThan(BigDecimal value) {
            addCriterion("origin_latitude <", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("origin_latitude <=", value, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeIn(List<BigDecimal> values) {
            addCriterion("origin_latitude in", values, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("origin_latitude not in", values, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("origin_latitude between", value1, value2, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("origin_latitude not between", value1, value2, "originLatitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeIsNull() {
            addCriterion("origin_longitude is null");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeIsNotNull() {
            addCriterion("origin_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeEqualTo(BigDecimal value) {
            addCriterion("origin_longitude =", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("origin_longitude <>", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeGreaterThan(BigDecimal value) {
            addCriterion("origin_longitude >", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("origin_longitude >=", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeLessThan(BigDecimal value) {
            addCriterion("origin_longitude <", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("origin_longitude <=", value, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeIn(List<BigDecimal> values) {
            addCriterion("origin_longitude in", values, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("origin_longitude not in", values, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("origin_longitude between", value1, value2, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("origin_longitude not between", value1, value2, "originLongitude");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeIsNull() {
            addCriterion("origin_cooridnation_type is null");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeIsNotNull() {
            addCriterion("origin_cooridnation_type is not null");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeEqualTo(String value) {
            addCriterion("origin_cooridnation_type =", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeNotEqualTo(String value) {
            addCriterion("origin_cooridnation_type <>", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeGreaterThan(String value) {
            addCriterion("origin_cooridnation_type >", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("origin_cooridnation_type >=", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeLessThan(String value) {
            addCriterion("origin_cooridnation_type <", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeLessThanOrEqualTo(String value) {
            addCriterion("origin_cooridnation_type <=", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeLike(String value) {
            addCriterion("origin_cooridnation_type like", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeNotLike(String value) {
            addCriterion("origin_cooridnation_type not like", value, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeIn(List<String> values) {
            addCriterion("origin_cooridnation_type in", values, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeNotIn(List<String> values) {
            addCriterion("origin_cooridnation_type not in", values, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeBetween(String value1, String value2) {
            addCriterion("origin_cooridnation_type between", value1, value2, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andOriginCooridnationTypeNotBetween(String value1, String value2) {
            addCriterion("origin_cooridnation_type not between", value1, value2, "originCooridnationType");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeIsNull() {
            addCriterion("baidu_latitude is null");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeIsNotNull() {
            addCriterion("baidu_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeEqualTo(BigDecimal value) {
            addCriterion("baidu_latitude =", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("baidu_latitude <>", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeGreaterThan(BigDecimal value) {
            addCriterion("baidu_latitude >", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("baidu_latitude >=", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeLessThan(BigDecimal value) {
            addCriterion("baidu_latitude <", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("baidu_latitude <=", value, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeIn(List<BigDecimal> values) {
            addCriterion("baidu_latitude in", values, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("baidu_latitude not in", values, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("baidu_latitude between", value1, value2, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("baidu_latitude not between", value1, value2, "baiduLatitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeIsNull() {
            addCriterion("baidu_longitude is null");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeIsNotNull() {
            addCriterion("baidu_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeEqualTo(BigDecimal value) {
            addCriterion("baidu_longitude =", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("baidu_longitude <>", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeGreaterThan(BigDecimal value) {
            addCriterion("baidu_longitude >", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("baidu_longitude >=", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeLessThan(BigDecimal value) {
            addCriterion("baidu_longitude <", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("baidu_longitude <=", value, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeIn(List<BigDecimal> values) {
            addCriterion("baidu_longitude in", values, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("baidu_longitude not in", values, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("baidu_longitude between", value1, value2, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andBaiduLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("baidu_longitude not between", value1, value2, "baiduLongitude");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andTextDescIsNull() {
            addCriterion("text_desc is null");
            return (Criteria) this;
        }

        public Criteria andTextDescIsNotNull() {
            addCriterion("text_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTextDescEqualTo(String value) {
            addCriterion("text_desc =", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescNotEqualTo(String value) {
            addCriterion("text_desc <>", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescGreaterThan(String value) {
            addCriterion("text_desc >", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescGreaterThanOrEqualTo(String value) {
            addCriterion("text_desc >=", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescLessThan(String value) {
            addCriterion("text_desc <", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescLessThanOrEqualTo(String value) {
            addCriterion("text_desc <=", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescLike(String value) {
            addCriterion("text_desc like", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescNotLike(String value) {
            addCriterion("text_desc not like", value, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescIn(List<String> values) {
            addCriterion("text_desc in", values, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescNotIn(List<String> values) {
            addCriterion("text_desc not in", values, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescBetween(String value1, String value2) {
            addCriterion("text_desc between", value1, value2, "textDesc");
            return (Criteria) this;
        }

        public Criteria andTextDescNotBetween(String value1, String value2) {
            addCriterion("text_desc not between", value1, value2, "textDesc");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}