package com.alct.integration.lbs.dao.mapper;

import com.alct.integration.lbs.dao.entity.PhoneLbsTraceEntity;
import com.alct.integration.lbs.dao.entity.PhoneLbsTraceEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PhoneLbsTraceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    long countByExample(PhoneLbsTraceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    int deleteByExample(PhoneLbsTraceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    int insert(PhoneLbsTraceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    int insertSelective(PhoneLbsTraceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    List<PhoneLbsTraceEntity> selectByExample(PhoneLbsTraceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PhoneLbsTraceEntity record, @Param("example") PhoneLbsTraceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_lbs_trace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PhoneLbsTraceEntity record, @Param("example") PhoneLbsTraceEntityExample example);
}